# Cloud Build configuration for Apna Journey Next.js app
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/apna-journey:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/apna-journey:latest'
      - '.'
    dir: '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/apna-journey:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/apna-journey:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'apna-journey'
      - '--image'
      - 'gcr.io/$PROJECT_ID/apna-journey:$COMMIT_SHA'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '1000'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'MONGODB_URI=MONGODB_URI:latest,JWT_SECRET=JWT_SECRET:latest,ADMIN_JWT_SECRET=ADMIN_JWT_SECRET:latest,CLOUDINARY_URL=CLOUDINARY_URL:latest,EMAIL_HOST=EMAIL_HOST:latest,EMAIL_PORT=EMAIL_PORT:latest,EMAIL_USER=EMAIL_USER:latest,EMAIL_PASS=EMAIL_PASS:latest,NEXTAUTH_URL=NEXTAUTH_URL:latest,NEXTAUTH_SECRET=NEXTAUTH_SECRET:latest,REDIS_URL=REDIS_URL:latest'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/apna-journey:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/apna-journey:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build
timeout: '1200s'
