export const BIHAR_LOCATIONS = [
  { value: 'patna', label: 'Patna', hindi: 'पटना' },
  { value: 'gaya', label: 'Gaya', hindi: 'गया' },
  { value: 'bhagalpur', label: 'Bhagalpur', hindi: 'भागलपुर' },
  { value: 'muzaffarpur', label: 'Muzaffarpur', hindi: 'मुजफ्फरपुर' },
  { value: 'darbhanga', label: 'Darbhanga', hindi: 'दरभंगा' },
  { value: 'purnia', label: 'Purnia', hindi: 'पूर्णिया' },
  { value: 'bihar-sharif', label: 'Bihar Sharif', hindi: 'बिहार शरीफ' },
  { value: 'arrah', label: 'Arrah', hindi: 'आरा' },
  { value: 'begusarai', label: 'Begusarai', hindi: 'बेगूसराय' },
  { value: 'katihar', label: 'Katihar', hindi: 'कटिहार' },
  { value: 'munger', label: 'Munger', hindi: 'मुंगेर' },
  { value: 'chapra', label: 'Chapra', hindi: 'छपरा' },
  { value: 'saharsa', label: 'Saharsa', hindi: 'सहरसा' },
  { value: 'sasaram', label: 'Sasaram', hindi: 'सासाराम' },
  { value: 'hajipur', label: 'Hajipur', hindi: 'हाजीपुर' },
  { value: 'dehri', label: 'Dehri', hindi: 'देहरी' },
  { value: 'bettiah', label: 'Bettiah', hindi: 'बेतिया' },
  { value: 'motihari', label: 'Motihari', hindi: 'मोतिहारी' },
  { value: 'buxar', label: 'Buxar', hindi: 'बक्सर' },
  { value: 'kishanganj', label: 'Kishanganj', hindi: 'किशनगंज' },
  { value: 'sitamarhi', label: 'Sitamarhi', hindi: 'सीतामढ़ी' },
  { value: 'gopalganj', label: 'Gopalganj', hindi: 'गोपालगंज' },
  { value: 'madhubani', label: 'Madhubani', hindi: 'मधुबनी' },
  { value: 'siwan', label: 'Siwan', hindi: 'सिवान' },
  { value: 'jehanabad', label: 'Jehanabad', hindi: 'जहानाबाद' },
  { value: 'aurangabad', label: 'Aurangabad', hindi: 'औरंगाबाद' },
  { value: 'nawada', label: 'Nawada', hindi: 'नवादा' },
  { value: 'jamui', label: 'Jamui', hindi: 'जमुई' },
  { value: 'lakhisarai', label: 'Lakhisarai', hindi: 'लखीसराय' },
  { value: 'sheikhpura', label: 'Sheikhpura', hindi: 'शेखपुरा' },
  { value: 'banka', label: 'Banka', hindi: 'बांका' },
  { value: 'arwal', label: 'Arwal', hindi: 'अरवल' },
  { value: 'sheohar', label: 'Sheohar', hindi: 'शिवहर' },
  { value: 'kaimur', label: 'Kaimur', hindi: 'कैमूर' },
  { value: 'rohtas', label: 'Rohtas', hindi: 'रोहतास' },
  { value: 'bhojpur', label: 'Bhojpur', hindi: 'भोजपुर' },
  { value: 'other', label: 'Other', hindi: 'अन्य' },
]

// Keep GAYA_LOCATIONS for backward compatibility
export const GAYA_LOCATIONS = BIHAR_LOCATIONS

export const BIHAR_DISTRICTS = [
  'Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Darbhanga', 'Purnia',
  'Bihar Sharif', 'Arrah', 'Begusarai', 'Katihar', 'Munger', 'Chapra',
  'Saharsa', 'Sasaram', 'Hajipur', 'Dehri', 'Bettiah', 'Motihari',
  'Buxar', 'Kishanganj', 'Sitamarhi', 'Gopalganj', 'Madhubani', 'Siwan',
  'Jehanabad', 'Aurangabad', 'Nawada', 'Jamui', 'Lakhisarai', 'Sheikhpura',
  'Banka', 'Arwal', 'Sheohar', 'Kaimur', 'Rohtas', 'Bhojpur'
]
